name: lineart-extractor
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch>=1.9.0
  - torchvision>=0.10.0
  - numpy>=1.21.0
  - opencv>=4.5.0
  - pillow>=8.3.0
  - pip
  - pip:
    - einops>=0.4.0